name: ackify-ce

services:
  ackify-db:
    image: postgres:16-alpine
    container_name: ackify-db-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: ackify_test
    volumes:
      - ackify_test:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ackify_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ackify-mailhog-test
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  minio:
    image: minio/minio:latest
    container_name: ackify-minio-test
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_test:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ackify_test:
  minio_test:
