name: ackify-ce

services:
  ackify-migrate:
    image: btouchard/ackify-ce
    container_name: ackify-migrate
    environment:
      ACKIFY_DB_DSN: "postgres://postgres:testpassword@ackify-db:5432/ackify_test?sslmode=disable"
      ACKIFY_APP_PASSWORD: "ackifytestpassword"
    depends_on:
      ackify-db:
        condition: service_healthy
    command: ["/app/migrate", "up"]
    entrypoint: []
    restart: "no"

  ackify-ce:
    build:
      context: .
      args:
        VERSION: "v0.0.0-dev"
        CYPRESS_COVERAGE: "true"
    image: btouchard/ackify-ce
    container_name: ackify-ce
    restart: unless-stopped
    environment:
      ACKIFY_LOG_LEVEL: "debug"
      ACKIFY_LOG_FORMAT: "classic"
      ACKIFY_BASE_URL: "http://localhost:8080"
      ACKIFY_ORGANISATION: "Ackify Test"
      ACKIFY_DB_DSN: "postgres://ackify_app:ackifytestpassword@ackify-db:5432/ackify_test?sslmode=disable"
      ACKIFY_AUTH_OAUTH_ENABLED: "true"
      ACKIFY_AUTH_MAGICLINK_ENABLED: "true"
      ACKIFY_OAUTH_PROVIDER: "custom"
      ACKIFY_OAUTH_CLIENT_ID: "test_client_id"
      ACKIFY_OAUTH_CLIENT_SECRET: "test_client_secret"
      ACKIFY_OAUTH_AUTH_URL: "https://auth.url.com/auth"
      ACKIFY_OAUTH_TOKEN_URL: "https://auth.url.com/token"
      ACKIFY_OAUTH_USERINFO_URL: "https://auth.url.com/userinfo"
      ACKIFY_OAUTH_COOKIE_SECRET: "dGVzdF9jb29raWVfc2VjcmV0X2Zvcl90ZXN0aW5nXzEyMzQ1Njc4OTA="
      ACKIFY_ED25519_PRIVATE_KEY: "kKjNo0cTUOdXcamyxYCcmGfUm7zXzeI8T2jaLEjvbcpA0IIO7HbR3ANBlUlqlWuV3D+RjDT+8p5o37n98+Wu5A=="
      ACKIFY_LISTEN_ADDR: ":8080"
      ACKIFY_ADMIN_EMAILS: "admin@test.com"
      ACKIFY_MAIL_HOST: "mailhog"
      ACKIFY_MAIL_PORT: "1025"
      ACKIFY_MAIL_TLS: "false"
      ACKIFY_MAIL_STARTTLS: "false"
      ACKIFY_MAIL_FROM: "noreply@ackify.test"
      ACKIFY_MAIL_FROM_NAME: "Ackify Test"
      ACKIFY_AUTH_MAGICLINK_RATE_LIMIT_EMAIL: "1000"
      ACKIFY_AUTH_MAGICLINK_RATE_LIMIT_IP: "1000"
      ACKIFY_AUTH_RATE_LIMIT: "1000"
      ACKIFY_DOCUMENT_RATE_LIMIT: "1000"
      ACKIFY_GENERAL_RATE_LIMIT: "1000"
      ACKIFY_TELEMETRY: false
      ACKIFY_STORAGE_TYPE: "local"
      ACKIFY_STORAGE_LOCAL_PATH: "/data/documents"
      ACKIFY_STORAGE_MAX_SIZE_MB: "50"
    volumes:
      - ackify_storage_e2e:/data/documents
    depends_on:
      ackify-migrate:
        condition: service_completed_successfully
      ackify-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/app/ackify", "health"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

  ackify-db:
    image: postgres:16-alpine
    container_name: ackify-db-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: ackify_test
    volumes:
      - ackify_test:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ackify_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ackify-mailhog-test
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  ackify_test:
  ackify_storage_e2e:
